modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "https://github.com/CreeperHost/BlockShot/blob/main/LICENSE.md"

[[mods]]
modId = "blockshot"
version = "${version}"
displayName = "BlockShot"
authors = "CreeperHost"
description = '''
Upload your screenshots for easy sharing
'''
#logoFile = ""

[[dependencies.blockshot]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockshot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20, 1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockshot]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.blockshot]]
modId = "polylib"
mandatory = true
versionRange = "[1200.0.2,)"
ordering = "AFTER"
side = "BOTH"
