modLoader = "javafml"
loaderVersion = "[38,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "blockshot"
version = "${version}"
displayName = "BlockShot"
authors = "CreeperHost"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.blockshot]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockshot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockshot]]
modId = "architectury"
mandatory = true
versionRange = "[3.4.9,)"
ordering = "AFTER"
side = "BOTH"
