modLoader = "javafml"
loaderVersion = "[48,)"
#issueTrackerURL = ""
license = "https://github.com/CreeperHost/BlockShot/blob/main/LICENSE.md"

[[mods]]
modId = "blockshot"
version = "${version}"
displayName = "BlockShot"
authors = "CreeperHost"
description = '''
Upload your screenshots for easy sharing
'''
#logoFile = ""

[[dependencies.blockshot]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockshot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockshot]]
modId = "architectury"
mandatory = true
versionRange = "[11.0.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.blockshot]]
modId = "polylib"
mandatory = true
versionRange = "[2004.0.3,)"
ordering = "AFTER"
side = "BOTH"
