modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "https://github.com/CreeperHost/BlockShot/blob/main/LICENSE.md"

[[mods]]
modId = "blockshot"
version = "${version}"
displayName = "BlockShot"
authors = "CreeperHost"
description = '''
Upload your screenshots for easy sharing
'''
#logoFile = ""

[[dependencies.blockshot]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockshot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockshot]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.46,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.blockshot]]
modId = "polylib"
mandatory = true
versionRange = "[1900.0.2,)"
ordering = "AFTER"
side = "BOTH"
