plugins {
    id "com.gradleup.shadow" version "9.2.2"
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

def ENV = System.getenv()

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation("net.creeperhost.polylib:polylib-fabric:${polylib_version}") { transitive = false }

    implementation("net.creeperhost:jcodec:0.2.6") { transitive = false }
    implementation("net.creeperhost:MineTogetherSessions:${mtsession_version}") { transitive = false }
    implementation("net.creeperhost:MineTogetherLib:${mtlib_version}") { transitive = false }
    implementation("net.covers1624:Quack:${quack_version}") { transitive = false }

    shadow("net.creeperhost:jcodec:0.2.6") { transitive = false }
    shadow("net.creeperhost:MineTogetherSessions:${mtsession_version}") { transitive = false }
    shadow("net.creeperhost:MineTogetherLib:${mtlib_version}") { transitive = false }
    shadow("net.covers1624:Quack:${quack_version}") { transitive = false }
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

shadowJar {
    dependsOn(jar)
    configurations = [project.configurations.shadow]
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))
    mergeServiceFiles()

    dependencies {
        exclude(dependency('com.google::'))
        exclude(dependency('org.apache::'))
    }
    relocate 'com.squareup.gifencoder', 'net.creeperhost.blockshot.com.squareup.gifencoder'
    relocate 'org.jcodec', 'net.creeperhost.blockshot.repack.org.jcodec'
    relocate 'net.sourceforge.jaad', 'net.creeperhost.blockshot.repack.net.sourceforge.jaad'
    relocate 'net.creeperhost.minetogether.session', 'net.creeperhost.blockshot.repack.net.creeperhost.minetogether.session'
    archiveClassifier = null
}

jar {
    archiveClassifier = 'dev'
}

configurations {
    [apiElements, runtimeElements].each { config ->
        config.outgoing.artifacts.clear()
        config.outgoing.artifact(shadowJar)
    }
}

assemble.dependsOn(shadowJar)

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}

publishing {
    publications {
        named('mavenJava', MavenPublication) {
            artifactId = rootProject.archives_base_name + "-fabric"
            version = "${rootProject.minecraft_version}-${rootProject.version}"
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        if (ENV.CREEPERHOST_MAVEN_TOKEN) {
            maven {
                url "https://maven.creeperhost.net/release"
                credentials {
                    username = "githubci"
                    password = "${ENV.CREEPERHOST_MAVEN_TOKEN}"
                }
            }
        }
    }
}

publishMods {
    file = shadowJar.archiveFile
    version = rootProject.publishMods.version
    changelog = rootProject.publishMods.changelog
    type = rootProject.publishMods.type
    displayName = "BlockShot ${project.version} for Fabric ${minecraft_version}"
    modLoaders.add('fabric')
    dryRun = rootProject.publishMods.dryRun

    github {
        accessToken = providers.environmentVariable('GITHUB_TOKEN')
        parent(rootProject.tasks.named('publishGithub'))
    }

    if (providers.environmentVariable('CURSEFORGE_PROJECT_ID').isPresent()) {
        curseforge {
            projectId = providers.environmentVariable('CURSEFORGE_PROJECT_ID')
            accessToken = providers.environmentVariable('CURSEFORGE_TOKEN')
            minecraftVersions.add(minecraft_version)
            client = true
            server = false
            requires('polylib')
            requires('fabric-api')
            dryRun = rootProject.publishMods.dryRun
        }
    }

    if (providers.environmentVariable('MODRINTH_PROJECT_ID').isPresent()) {
        modrinth {
            projectId = providers.environmentVariable('MODRINTH_PROJECT_ID')
            accessToken = providers.environmentVariable('MODRINTH_TOKEN')
            minecraftVersions.add(minecraft_version)
            environment = CLIENT_ONLY
            requires('6lvkzFFj')
            requires('P7dR8mSH')
            dryRun = rootProject.publishMods.dryRun
        }
    }
}
