org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=false

version=1.5.1
group=net.creeperhost.blockshot
java_version=25

minecraft_version=26.1.2
minecraft_version_range=[26.1.2, 26.2)
neo_form_version=26.1.2-1

archives_base_name=blockshot
mod_name=BlockShot
mod_author=CreeperHost
mod_id=blockshot
license=https://github.com/CreeperHost/BlockShot/blob/main/LICENSE.md
credits=
description=Upload your screenshots for easy sharing

fabric_loader_version=0.19.2
fabric_version=0.146.1+26.1.2

neoforge_version=26.1.2.75
neoforge_loader_version_range=[4,)

mtsession_version=1.2.7
mtlib_version=3.6
polylib_version=26.1.2-2.0.9
polylib_mod_version=2.0.8
quack_version=0.4.10.105

artifact_type=release
curseforge_id=571107
modrinth_id=UymUHj8N
