plugins {
    id "com.github.johnrengelman.shadow" version "7.0.0"
    id "maven-publish"
}

architectury {
    common("fabric", "forge", "neoforge")
}

loom {
    accessWidenerPath = file("src/main/resources/blockshot.accesswidener")
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi ("dev.architectury:architectury:${rootProject.architectury_version}")
    modApi ("net.creeperhost:polylib-fabric:${polylib_version}") { transitive = false }
    modApi ("net.creeperhost:jcodec:0.2.6") { transitive = false }
    modApi ("net.creeperhost:MineTogetherSessions:${mtsession_version}") { transitive = false }
    modApi ("curse.maven:creeperhost-minetogether-267172:5522847") { transitive = false }
    modApi ("net.creeperhost:MineTogetherLib:${mtlib_version}") { transitive = false }
    modApi ("net.covers1624:Quack:${quack_version}") { transitive = false }
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name
            from components.java
        }
    }
}
